#
# OCI Native Ingress Controller
#
# Copyright (c) 2023 Oracle America, Inc. and its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oci-native-ingress-controller.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "oci-native-ingress-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: webhook-server
      port: 443
      protocol: TCP
      targetPort: webhook-server
  selector:
    {{- include "oci-native-ingress-controller.selectorLabels" . | nindent 4 }}
