---
# Source: oci-native-ingress-controller/crds/ingress.oraclecloud.com_ingressclassparameters.yaml
#
# OCI Native Ingress Controller
#
# Copyright (c) 2023 Oracle America, Inc. and its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressclassparameters.ingress.oraclecloud.com
spec:
  group: ingress.oraclecloud.com
  names:
    kind: IngressClassParameters
    listKind: IngressClassParametersList
    plural: ingressclassparameters
    singular: ingressclassparameters
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.loadBalancerName
      name: LoadBalancerName
      type: string
    - jsonPath: .spec.compartmentId
      name: Compartment
      type: string
    - jsonPath: .spec.isPrivate
      name: Private
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: IngressClassParameters is the Schema for the IngressClassParameters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: IngressClassParametersSpec defines the desired state of IngressClassParameters
            properties:
              compartmentId:
                maxLength: 255
                minLength: 1
                type: string
              isPrivate:
                type: boolean
              loadBalancerName:
                type: string
              maxBandwidthMbps:
                default: 100
                maximum: 8000
                minimum: 10
                type: integer
              minBandwidthMbps:
                default: 10
                maximum: 8000
                minimum: 10
                type: integer
              reservedPublicAddressId:
                type: string
              subnetId:
                maxLength: 255
                minLength: 1
                type: string
            type: object
          status:
            description: IngressClassParametersStatus defines the observed state of IngressClassParameters
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

