---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-readiness
  namespace: default
spec:
  rules:
    - host: "foo.bar.com"
      http:
        paths:
          - pathType: Exact
            path: "/service-with-named-target-port"
            backend:
              service:
                name: service-with-named-target-port
                port:
                  number: 8081
    - host: "foo.bar.com1"
      http:
        paths:
          - pathType: Exact
            path: "/service-with-numeric-target-port"
            backend:
              service:
                name: service-with-named-target-port
                port:
                  name: "port_8082"